### ISSUE TITLE
Rename generated model

### ISSUE THREAD

**Issue by mesemus** [oarepo/oarepo-model-builder-files#2]
Currently the generated test model is called "test" - which brings some confusion with "tests" directory, especially if the "omb-tests"plugin is installed:

<img width="312" alt="image" src="https://user-images.githubusercontent.com/3385642/216059694-1c97963a-4cfa-47f5-94be-59d5c29ae409.png">

**Comment by mirekys** [comment]
Fixed in https://github.com/oarepo/oarepo-model-builder-files/commit/332eb65fe9af51c0147f927890ef629d4e3fb318
